version: '3.5'
services:    
    mwtt: 
        image: tmunzer/mwtt
        container_name: "mist-mwtt-standalone"
        ports:
            - "80:51361"
        volumes:
            - /mist_webhooks/config.py:/app/config.py:ro  
